class NetworkError(Exception):
    pass

class ConnectionClosed(Exception):
    pass